services:
  web:
    build: ./24h-secret
    ports:
      - "3000:3000"
    env_file:
      - ./24h-secret/.env.local

  admin:
    build: ./24h-secret-admin
    ports:
      - "3001:3001"
    env_file:
      - ./24h-secret-admin/.env.local
